package com.manager.model.mapper;

import com.manager.model.entity.SaleOrder;
import com.manager.model.entity.SaleOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    long countByExample(SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int deleteByExample(SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int insert(SaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int insertSelective(SaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    List<SaleOrder> selectByExample(SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    SaleOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleOrder record, @Param("example") SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int updateByExample(@Param("record") SaleOrder record, @Param("example") SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int updateByPrimaryKeySelective(SaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    int updateByPrimaryKey(SaleOrder record);
}