package com.manager.model.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FinanceProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.id
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.name
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.threshold_amount
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private BigDecimal thresholdAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.step_amount
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private BigDecimal stepAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.lock_term
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private Integer lockTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.reward_rate
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private BigDecimal rewardRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.status
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.memo
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.create_time
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.create_user
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.update_time
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.update_user
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table finance_product
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.id
     *
     * @return the value of finance_product.id
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.id
     *
     * @param id the value for finance_product.id
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.name
     *
     * @return the value of finance_product.name
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.name
     *
     * @param name the value for finance_product.name
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.threshold_amount
     *
     * @return the value of finance_product.threshold_amount
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public BigDecimal getThresholdAmount() {
        return thresholdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.threshold_amount
     *
     * @param thresholdAmount the value for finance_product.threshold_amount
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setThresholdAmount(BigDecimal thresholdAmount) {
        this.thresholdAmount = thresholdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.step_amount
     *
     * @return the value of finance_product.step_amount
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public BigDecimal getStepAmount() {
        return stepAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.step_amount
     *
     * @param stepAmount the value for finance_product.step_amount
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setStepAmount(BigDecimal stepAmount) {
        this.stepAmount = stepAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.lock_term
     *
     * @return the value of finance_product.lock_term
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public Integer getLockTerm() {
        return lockTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.lock_term
     *
     * @param lockTerm the value for finance_product.lock_term
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setLockTerm(Integer lockTerm) {
        this.lockTerm = lockTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.reward_rate
     *
     * @return the value of finance_product.reward_rate
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public BigDecimal getRewardRate() {
        return rewardRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.reward_rate
     *
     * @param rewardRate the value for finance_product.reward_rate
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setRewardRate(BigDecimal rewardRate) {
        this.rewardRate = rewardRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.status
     *
     * @return the value of finance_product.status
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.status
     *
     * @param status the value for finance_product.status
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.memo
     *
     * @return the value of finance_product.memo
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.memo
     *
     * @param memo the value for finance_product.memo
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.create_time
     *
     * @return the value of finance_product.create_time
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.create_time
     *
     * @param createTime the value for finance_product.create_time
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.create_user
     *
     * @return the value of finance_product.create_user
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.create_user
     *
     * @param createUser the value for finance_product.create_user
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.update_time
     *
     * @return the value of finance_product.update_time
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.update_time
     *
     * @param updateTime the value for finance_product.update_time
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.update_user
     *
     * @return the value of finance_product.update_user
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.update_user
     *
     * @param updateUser the value for finance_product.update_user
     *
     * @mbg.generated Mon Aug 19 14:58:38 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}