package com.manager.model.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SaleOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.order_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.chan_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String chanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.product_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.chan_user_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String chanUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.order_type
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.order_status
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.outer_order_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String outerOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.amount
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.memo
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.create_at
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.update_at
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.order_id
     *
     * @return the value of sale_order.order_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.order_id
     *
     * @param orderId the value for sale_order.order_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.chan_id
     *
     * @return the value of sale_order.chan_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getChanId() {
        return chanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.chan_id
     *
     * @param chanId the value for sale_order.chan_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setChanId(String chanId) {
        this.chanId = chanId == null ? null : chanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.product_id
     *
     * @return the value of sale_order.product_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.product_id
     *
     * @param productId the value for sale_order.product_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.chan_user_id
     *
     * @return the value of sale_order.chan_user_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getChanUserId() {
        return chanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.chan_user_id
     *
     * @param chanUserId the value for sale_order.chan_user_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setChanUserId(String chanUserId) {
        this.chanUserId = chanUserId == null ? null : chanUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.order_type
     *
     * @return the value of sale_order.order_type
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.order_type
     *
     * @param orderType the value for sale_order.order_type
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.order_status
     *
     * @return the value of sale_order.order_status
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.order_status
     *
     * @param orderStatus the value for sale_order.order_status
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.outer_order_id
     *
     * @return the value of sale_order.outer_order_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getOuterOrderId() {
        return outerOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.outer_order_id
     *
     * @param outerOrderId the value for sale_order.outer_order_id
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setOuterOrderId(String outerOrderId) {
        this.outerOrderId = outerOrderId == null ? null : outerOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.amount
     *
     * @return the value of sale_order.amount
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.amount
     *
     * @param amount the value for sale_order.amount
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.memo
     *
     * @return the value of sale_order.memo
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.memo
     *
     * @param memo the value for sale_order.memo
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.create_at
     *
     * @return the value of sale_order.create_at
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.create_at
     *
     * @param createAt the value for sale_order.create_at
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.update_at
     *
     * @return the value of sale_order.update_at
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.update_at
     *
     * @param updateAt the value for sale_order.update_at
     *
     * @mbg.generated Mon Aug 12 20:53:12 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}