spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/?user=root&password=123456&useUnicode=true&characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
server:
  servlet:
    context-path: /manager
  port: 8081


# 日志配置
logging:
  level:
    com.googlecode.jsonrpc4j: debug


#mapper-locations:
#    - classpath: mapper/*.xml
#    - classpath: dao/*.xml

# mybatis 配置
mybatis:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl